//! A local language model, served by Ollama.
//!
//! It is the suggestion engine's last resort: it picks among valid words when
//! the history has no opinion, and proposes the next word when nothing else
//! has one. The model runs on this machine, and prompts leave out command lines
//! that look like they carry credentials.

use std::time::Duration;

use serde_json::{Value, json};

/// Default Ollama endpoint.
pub const DEFAULT_URL: &str = "http://127.0.0.1:11434";

/// Default model: small and fast, trained on code, shell included.
pub const DEFAULT_MODEL: &str = "qwen2.5-coder:1.5b-base";

const KEEP_ALIVE: &str = "1h";
const TOP_LOGPROBS: u32 = 20;
const MAX_PROMPT_LINE: usize = 200;

/// Something that continues text.
pub trait Oracle: Send + Sync {
    /// The likeliest next tokens after `prompt`, with their log-probabilities.
    fn next_tokens(&self, prompt: &str) -> Result<Vec<(String, f64)>, LlmError>;

    /// Continues `prompt` up to the end of its line.
    fn complete(&self, prompt: &str) -> Result<Continuation, LlmError>;
}

/// Text generated by the model, token by token.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Continuation {
    /// The generated text.
    pub text: String,
    /// Its tokens, in order, with their log-probabilities.
    pub tokens: Vec<(String, f64)>,
}

impl Continuation {
    /// Probability of the first `len` bytes of the text: the product of the
    /// probabilities of the tokens that cover them; 0 when the tokens are
    /// missing.
    pub fn probability_of_prefix(&self, len: usize) -> f64 {
        let mut covered = 0;
        let mut logprob = 0.0;
        for (token, token_logprob) in &self.tokens {
            if covered >= len {
                break;
            }
            covered += token.len();
            logprob += token_logprob;
        }
        if covered < len { 0.0 } else { logprob.exp() }
    }
}

/// Why the model gave no answer.
#[derive(Debug, thiserror::Error)]
pub enum LlmError {
    /// The request failed or timed out.
    #[error("request to the model failed: {0}")]
    Request(#[source] ureq::Error),
    /// The response could not be read as JSON.
    #[error("unreadable response from the model: {0}")]
    Decode(#[source] ureq::Error),
    /// The response is not what Ollama sends.
    #[error("unexpected response from the model: {0}")]
    Response(&'static str),
}

/// An [`Oracle`] backed by Ollama's `/api/generate`.
pub struct Ollama {
    endpoint: String,
    model: String,
    agent: ureq::Agent,
}

impl Ollama {
    /// A client for `model` at `url` that gives up on a request after `timeout`.
    pub fn new(url: &str, model: &str, timeout: Duration) -> Self {
        Self {
            endpoint: format!("{}/api/generate", url.trim_end_matches('/')),
            model: model.to_owned(),
            agent: agent(timeout),
        }
    }

    /// Loads the model into memory, so that the first suggestion does not wait
    /// for it.
    pub fn warm_up(&self, timeout: Duration) -> Result<(), LlmError> {
        self.generate(&agent(timeout), "$ ", 1, false).map(drop)
    }

    fn generate(
        &self,
        agent: &ureq::Agent,
        prompt: &str,
        tokens: u32,
        alternatives: bool,
    ) -> Result<Value, LlmError> {
        let mut body = json!({
            "model": self.model,
            "prompt": prompt,
            "raw": true,
            "stream": false,
            "keep_alive": KEEP_ALIVE,
            "options": {"temperature": 0, "num_predict": tokens, "stop": ["\n"]},
            "logprobs": true,
        });
        if alternatives {
            body["top_logprobs"] = json!(TOP_LOGPROBS);
        }
        agent
            .post(&self.endpoint)
            .send_json(&body)
            .map_err(LlmError::Request)?
            .body_mut()
            .read_json()
            .map_err(LlmError::Decode)
    }
}

impl Oracle for Ollama {
    fn next_tokens(&self, prompt: &str) -> Result<Vec<(String, f64)>, LlmError> {
        parse_top_logprobs(&self.generate(&self.agent, prompt, 1, true)?)
    }

    fn complete(&self, prompt: &str) -> Result<Continuation, LlmError> {
        parse_continuation(&self.generate(&self.agent, prompt, 16, false)?)
    }
}

/// An agent that goes straight to the model. ureq would otherwise take a proxy
/// from `http_proxy` or `ALL_PROXY`, and unless `NO_PROXY` lists the loopback
/// address, hand the prompts, recent commands included, to that proxy.
fn agent(timeout: Duration) -> ureq::Agent {
    ureq::Agent::config_builder()
        .timeout_global(Some(timeout))
        .proxy(None)
        .build()
        .new_agent()
}

/// The generated text and its tokens, from a `/api/generate` response.
fn parse_continuation(response: &Value) -> Result<Continuation, LlmError> {
    let text = response["response"]
        .as_str()
        .ok_or(LlmError::Response("no text in the response"))?;
    let tokens = response["logprobs"]
        .as_array()
        .map(|tokens| {
            tokens
                .iter()
                .filter_map(|token| {
                    Some((
                        token["token"].as_str()?.to_owned(),
                        token["logprob"].as_f64()?,
                    ))
                })
                .collect()
        })
        .unwrap_or_default();
    Ok(Continuation {
        text: text.to_owned(),
        tokens,
    })
}

/// The alternatives for the first generated token, from a `/api/generate`
/// response.
fn parse_top_logprobs(response: &Value) -> Result<Vec<(String, f64)>, LlmError> {
    let alternatives = response["logprobs"][0]["top_logprobs"]
        .as_array()
        .ok_or(LlmError::Response("no log-probabilities in the response"))?;
    Ok(alternatives
        .iter()
        .filter_map(|alternative| {
            let token = alternative["token"].as_str()?;
            Some((token.to_owned(), alternative["logprob"].as_f64()?))
        })
        .collect())
}

/// A prompt showing recent commands as a shell session that ends with `line`,
/// for the model to continue the way the session would.
pub fn prompt<'a>(
    cwd: Option<&str>,
    recent: impl IntoIterator<Item = &'a str>,
    line: &str,
) -> String {
    let mut prompt = match cwd {
        Some(cwd) => format!("# bash session in {cwd}\n"),
        None => "# bash session\n".to_owned(),
    };
    for command in recent
        .into_iter()
        .filter(|command| command.len() <= MAX_PROMPT_LINE && !looks_secret(command))
    {
        prompt.push_str("$ ");
        prompt.push_str(command);
        prompt.push('\n');
    }
    prompt.push_str("$ ");
    prompt.push_str(line);
    prompt
}

/// Whether a command line probably carries a credential. A list of words that
/// go with credentials, not a scanner: `mysql -pXXX` or a bare token pass.
pub fn looks_secret(command: &str) -> bool {
    const NEEDLES: [&str; 12] = [
        "password",
        "passwd",
        "secret",
        "token",
        "apikey",
        "api_key",
        "api-key",
        "authorization",
        "bearer ",
        "private_key",
        "aws_access",
        "aws_secret",
    ];
    let lower = command.to_lowercase();
    NEEDLES.iter().any(|needle| lower.contains(needle))
}

#[cfg(test)]
mod tests {
    use std::io::{BufRead, BufReader, Read, Write};
    use std::net::TcpListener;
    use std::thread;

    use super::*;

    #[test]
    fn prompt_is_a_shell_session_without_secrets() {
        let recent = [
            "git status",
            "curl -H 'Authorization: Bearer abc' x",
            "cargo test",
        ];
        assert_eq!(
            prompt(Some("/work"), recent, "kubectl get po"),
            "# bash session in /work\n$ git status\n$ cargo test\n$ kubectl get po"
        );
    }

    #[test]
    fn measures_the_probability_of_a_prefix() {
        let continuation = parse_continuation(&json!({
            "response": " libx264 -c",
            "logprobs": [
                {"token": " lib", "logprob": -0.1},
                {"token": "x264", "logprob": -0.2},
                {"token": " -c", "logprob": -2.0}
            ]
        }))
        .expect("continuation");
        assert_eq!(continuation.text, " libx264 -c");
        let word = continuation.probability_of_prefix(" libx264".len());
        assert!((word - (-0.3f64).exp()).abs() < 1e-9, "{word}");
        assert_eq!(continuation.probability_of_prefix(100), 0.0);
    }

    #[test]
    fn parses_the_first_token_alternatives() {
        let response = json!({
            "response": "erryp",
            "logprobs": [{
                "token": "err",
                "logprob": -1.5,
                "top_logprobs": [
                    {"token": "err", "logprob": -1.5, "bytes": [101, 114, 114]},
                    {"token": "eck", "logprob": -2.0, "bytes": [101, 99, 107]}
                ]
            }]
        });
        let alternatives = parse_top_logprobs(&response).expect("alternatives");
        assert_eq!(
            alternatives,
            [("err".to_owned(), -1.5), ("eck".to_owned(), -2.0)]
        );
        assert!(parse_top_logprobs(&json!({"response": ""})).is_err());
    }

    /// Serves one canned `/api/generate` response and returns the request body.
    fn serve_once(response: Value) -> (String, thread::JoinHandle<String>) {
        let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
        let url = format!("http://{}", listener.local_addr().expect("address"));
        let server = thread::spawn(move || {
            let (stream, _) = listener.accept().expect("accept");
            let mut reader = BufReader::new(stream);
            let mut length = 0;
            loop {
                let mut line = String::new();
                reader.read_line(&mut line).expect("header");
                if line == "\r\n" {
                    break;
                }
                if let Some(value) = line.to_lowercase().strip_prefix("content-length:") {
                    length = value.trim().parse().expect("length");
                }
            }
            let mut body = vec![0; length];
            reader.read_exact(&mut body).expect("body");
            let payload = response.to_string();
            write!(
                reader.get_mut(),
                "HTTP/1.1 200 OK\r\ncontent-type: application/json\r\ncontent-length: {}\r\n\r\n{payload}",
                payload.len()
            )
            .expect("respond");
            String::from_utf8(body).expect("utf-8 body")
        });
        (url, server)
    }

    #[test]
    fn asks_ollama_for_the_next_token_alternatives() {
        let (url, server) = serve_once(json!({
            "response": "ds",
            "logprobs": [{"token": "ds", "logprob": -0.1, "top_logprobs": [{"token": "ds", "logprob": -0.1}]}]
        }));
        let ollama = Ollama::new(&url, "some-model", Duration::from_secs(5));
        let alternatives = ollama
            .next_tokens("$ kubectl get po")
            .expect("alternatives");
        assert_eq!(alternatives, [("ds".to_owned(), -0.1)]);

        let request: Value = serde_json::from_str(&server.join().expect("server")).expect("json");
        assert_eq!(request["model"], "some-model");
        assert_eq!(request["prompt"], "$ kubectl get po");
        assert_eq!(request["raw"], true);
        assert_eq!(request["options"]["num_predict"], 1);
        assert_eq!(request["top_logprobs"], TOP_LOGPROBS);
    }

    #[test]
    fn reports_an_unreachable_server() {
        let ollama = Ollama::new("http://127.0.0.1:9", "m", Duration::from_millis(200));
        assert!(matches!(ollama.complete("$ ls"), Err(LlmError::Request(_))));
    }
}
